(in-package :kieneman)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Types
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defmacro def-cp (type-name)
  "Creates a def-c-type form which sets 'type-name' to
type c-pointer. Used by the CLISP ffi."
  `(def-c-type ,type-name c-pointer))

(defmacro with-def-c-type (type alias-list)
  "Declares all the symbols in the body to be aliases of
c-type type"
  `(progn
     ,@(mapcar
	#'(lambda (alias) `(def-c-type ,alias ,type))
	alias-list)))


;;All types below are c-pointers
(defun define-types ()
 (with-def-c-type c-pointer
		  (input-toggle
		   root
		   scene-manager
		   node
		   scene-node
		   entity
		   manual-object
		   camera
		   vector3
		   quaternion
		   degree
		   radian
		   viewport
		   light
		   tex-area-overlay-element))

					;(def-cp input-toggle)
					;(def-cp root)

 (def-c-enum scene-type
   (ST_GENERIC 1)
   (ST_EXTERIOR_CLOSE 2)
   (ST_EXTERIOR_FAR 4)
   (ST_EXTERIOR_REAL_FAR 8)
   (ST_INTERIOR 1))

 (def-c-enum transform-space
   (TS_LOCAL)
   (TS_PARENT)
   (TS_WORLD))

 (def-c-enum keycode
   (KC_UNASSIGNED #x00)
   (KC_ESCAPE #x01)
   (KC_1 #x02)
   (KC_2 #x03)
   (KC_3 #x04)
   (KC_4 #x05)
   (KC_5 #x06)
   (KC_6 #x07)
   (KC_7 #x08)
   (KC_8 #x09)
   (KC_9 #x0A)
   (KC_0 #x0B)
   (KC_MINUS #x0C)
   (KC_EQUALS #x0D)
   (KC_BACK #x0E)
   (KC_TAB #x0F)
   (KC_Q #x10)
   (KC_W #x11)
   (KC_E #x12)
   (KC_R #x13)
   (KC_T #x14)
   (KC_Y #x15)
   (KC_U #x16)
   (KC_I #x17)
   (KC_O #x18)
   (KC_P #x19)
   (KC_LBRACKET #x1A)
   (KC_RBRACKET #x1B)
   (KC_RETURN #x1C)
   (KC_LCONTROL #x1D)
   (KC_A #x1E)
   (KC_S #x1F)
   (KC_D #x20)
   (KC_F #x21)
   (KC_G #x22)
   (KC_H #x23)
   (KC_J #x24)
   (KC_K #x25)
   (KC_L #x26)
   (KC_SEMICOLON #x27)
   (KC_APOSTROPHE #x28)
   (KC_GRAVE #x29)
   (KC_LSHIFT #x2A)
   (KC_BACKSLASH #x2B)
   (KC_Z #x2C)
   (KC_X #x2D)
   (KC_C #x2E)
   (KC_V #x2F)
   (KC_B #x30)
   (KC_N #x31)
   (KC_M #x32)
   (KC_COMMA #x33)
   (KC_PERIOD #x34)
   (KC_SLASH #x35)
   (KC_RSHIFT #x36)
   (KC_MULTIPLY #x37)
   (KC_LMENU #x38)
   (KC_SPACE #x39)
   (KC_CAPITAL #x3A)
   (KC_F1 #x3B)
   (KC_F2 #x3C)
   (KC_F3 #x3D)
   (KC_F4 #x3E)
   (KC_F5 #x3F)
   (KC_F6 #x40)
   (KC_F7 #x41)
   (KC_F8 #x42)
   (KC_F9 #x43)
   (KC_F10 #x44)
   (KC_NUMLOCK #x45)
   (KC_SCROLL #x46)
   (KC_NUMPAD7 #x47)
   (KC_NUMPAD8 #x48)
   (KC_NUMPAD9 #x49)
   (KC_SUBTRACT #x4A)
   (KC_NUMPAD4 #x4B)
   (KC_NUMPAD5 #x4C)
   (KC_NUMPAD6 #x4D)
   (KC_ADD #x4E)
   (KC_NUMPAD1 #x4F)
   (KC_NUMPAD2 #x50)
   (KC_NUMPAD3 #x51)
   (KC_NUMPAD0 #x52)
   (KC_DECIMAL #x53)
   (KC_OEM_102 #x56)
   (KC_F11 #x57)
   (KC_F12 #x58)
   (KC_F13 #x64)
   (KC_F14 #x65)
   (KC_F15 #x66)
   (KC_KANA #x70)
   (KC_ABNT_C1 #x73)
   (KC_CONVERT #x79)
   (KC_NOCONVERT #x7B)
   (KC_YEN #x7D)
   (KC_ABNT_C2 #x7E)
   (KC_NUMPADEQUALS #x8D)
   (KC_PREVTRACK #x90)
   (KC_AT #x91)
   (KC_COLON #x92)
   (KC_UNDERLINE #x93)
   (KC_KANJI #x94)
   (KC_STOP #x95)
   (KC_AX #x96)
   (KC_UNLABELED #x97)
   (KC_NEXTTRACK #x99)
   (KC_NUMPADENTER #x9C)
   (KC_RCONTROL #x9D)
   (KC_MUTE #xA0)
   (KC_CALCULATOR #xA1)
   (KC_PLAYPAUSE #xA2)
   (KC_MEDIASTOP #xA4)
   (KC_VOLUMEDOWN #xAE)
   (KC_VOLUMEUP #xB0)
   (KC_WEBHOME #xB2)
   (KC_NUMPADCOMMA #xB3)
   (KC_DIVIDE #xB5)
   (KC_SYSRQ #xB7)
   (KC_RMENU #xB8)
   (KC_PAUSE #xC5)
   (KC_HOME #xC7)
   (KC_UP #xC8)
   (KC_PGUP #xC9)
   (KC_LEFT #xCB)
   (KC_RIGHT #xCD)
   (KC_END #xCF)
   (KC_DOWN #xD0)
   (KC_PGDOWN #xD1)
   (KC_INSERT #xD2)
   (KC_DELETE #xD3)
   (KC_LWIN #xDB)
   (KC_RWIN #xDC)
   (KC_APPS #xDD)
   (KC_POWER #xDE)
   (KC_SLEEP #xDF)
   (KC_WAKE #xE3)
   (KC_WEBSEARCH #xE5)
   (KC_WEBFAVORITES #xE6)
   (KC_WEBREFRESH #xE7)
   (KC_WEBSTOP #xE8)
   (KC_WEBFORWARD #xE9)
   (KC_WEBBACK #xEA)
   (KC_MYCOMPUTER #xEB)
   (KC_MAIL #xEC)
   (KC_MEDIASELECT #xED)))

(define-types)